### ISSUE TITLE
React hooks issue

### ISSUE THREAD

**Issue by nctay** [ganapativs/react-dynamic-import#47] opened 2019-12-30 11:48 UTC
Hi! 
I have trouble with last versions that use hooks. 
When using any of this versions i got "Invalid Hook Call Warning".
v1.0.4 works fine, no errors.
React version is 
![image](https://user-images.githubusercontent.com/36993061/71580821-62316a00-2b13-11ea-97ef-b85a6ea01a79.png)
What else can i do, to make newer versions work ?
Thanks for this amazing lib, though :)

**Comment by ganapativs** [comment] 2020-01-07 16:24
Hey, Sorry for the delayed response.

`react-dynamic-import` versions after `1.0.4` should work fine with any `react` versions `>16.8.0`.

If you are getting [`Invalid Hooks Call Warning`](https://reactjs.org/warnings/invalid-hook-call-warning.html), possibly there are multiple `react` versions or you have mismatching `react` & `react-dom` versions. If you are using `webpack` or any other bundler, just alias `react` to the latest/your version.

Checkout working hooks example here: https://codesandbox.io/s/react-dynamic-import-hooks-demo-108-kuf3u

**Comment by ganapativs** [comment] 2020-01-13 15:49
I hope the issue is resolved by now. closing for now. re-open if you have any questions.

**Closed by ganapativs** 2020-01-13 15:49 UTC
Labels: question
